### ISSUE TITLE
Turning mining on crashes

### ISSUE THREAD

**Issue by chfast** [ethereum/alethzero#53]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff37ae080 in QAction::isChecked() const () from /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff37ae080 in QAction::isChecked() const () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#1  0x00000000005e0219 in dev::aleth::zero::Mining::Mining(dev::aleth::zero::ZeroFace*)::{lambda()#1}::operator()() const ()
#2  0x00000000005e17b0 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, dev::aleth::zero::Mining::Mining(dev::aleth::zero::ZeroFace*)::{lambda()#1}>::call({lambda()#1}, void**) ()
#3  0x00000000005e168c in void QtPrivate::Functor<dev::aleth::zero::Mining::Mining(dev::aleth::zero::ZeroFace*)::{lambda()#1}, 0>::call<QtPrivate::List<>, void>({lambda()#1}&, void*, {lambda()#1}&*) ()
#4  0x00000000005e1493 in QtPrivate::QFunctorSlotObject<dev::aleth::zero::Mining::Mining(dev::aleth::zero::ZeroFace*)::{lambda()#1}, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) ()
#5  0x00007ffff1ec51d5 in QMetaObject::activate(QObject*, int, int, void**) () at /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#6  0x00007ffff37ac6b2 in QAction::triggered(bool) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#7  0x00007ffff37ae4d7 in QAction::activate(QAction::ActionEvent) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#8  0x00007ffff39357ea in  () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#9  0x00007ffff393cf0f in  () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#10 0x00007ffff393de50 in QMenu::mouseReleaseEvent(QMouseEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#11 0x00007ffff37f4b9c in QWidget::event(QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#12 0x00007ffff393fc5b in QMenu::event(QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#13 0x00007ffff37b92b4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#14 0x00007ffff37bca4c in QApplication::notify(QObject*, QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#15 0x00007ffff1e92e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#16 0x00007ffff37bb978 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#17 0x00007ffff380f82e in  () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#18 0x00007ffff3812648 in  () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#19 0x00007ffff37b92b4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#20 0x00007ffff37bcc86 in QApplication::notify(QObject*, QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#21 0x00007ffff1e92e24 in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#22 0x00007ffff2d60fa7 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#23 0x00007ffff2d61a35 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
    at /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#24 0x00007ffff2d46728 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /opt/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#25 0x00007fffd9343a10 in  () at /opt/Qt/5.4/gcc_64/plugins/platforms/libqxcb.so
#26 0x00007fffe948ec3d in g_main_context_dispatch (context=0x7fffd40016f0) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3122
#27 0x00007fffe948ec3d in g_main_context_dispatch (context=context@entry=0x7fffd40016f0) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3737
#28 0x00007fffe948ef20 in g_main_context_iterate (context=context@entry=0x7fffd40016f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3808
#29 0x00007fffe948efcc in g_main_context_iteration (context=0x7fffd40016f0, may_block=1) at /build/buildd/glib2.0-2.44.1/./glib/gmain.c:3869
---Type <return> to continue, or q <return> to quit---
#30 0x00007ffff1eed5e4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#31 0x00007ffff1e9104b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#32 0x00007ffff1e95f65 in QCoreApplication::exec() () at /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#33 0x00000000006454db in main ()
```

**Comment by CJentzsch** [comment]
got the same: https://gist.github.com/CJentzsch/f27dacd54e95741f5960
And why are there 57 threads open? Qt is very demanding.
